# Based on: https://github.com/jdblischak/smk-simple-slurm
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - account=perrybe
  - partition=inv-iranui,inv-blade-g8
  - qos=normal
  - cpus-per-task=2
  - time="02:00:00"
  - mem_mb=8000
restart-times: 5
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 4
latency-wait: 6000
jobs: 12
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
use-singularity: True
reason: True